djangopractice/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^study/', include('practice.urls')),
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

practice/urls.py
from django.conf.urls import url
from .views import PublisherList, AuthorCreate, AuthorUpdate, AuthorDelete,PostView ,post_detail,api_response,api_list,project_list

app_name = 'practice'

urlpatterns = [
    url(r'^publishers/$', PublisherList.as_view()),
    url(r'^posts/$', PostView.as_view(), name='posts'),
    url(r'^post/(?P<pk>[0-9]+)/$', post_detail, name='post_detail'),
    url(r'author/add/$', AuthorCreate.as_view(), name='author-add'),
    url(r'author/(?P<pk>[0-9]+)/$', AuthorUpdate.as_view(), name='author-update'),
    url(r'author/(?P<pk>[0-9]+)/delete/$', AuthorDelete.as_view(), name='author-delete'),

    url(r'^api/(?P<project_name>\w+)/(?P<api_name>\w+)$', api_response, name='api_response'),
    url(r'^api/(?P<project_name>\w+)/$', api_list, name='api_list'),
    url(r'^api/$', project_list ,name='projects'),
]

practice/models.py
from django.db import models
from django.utils import timezone
from ckeditor.fields import RichTextField

class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()

    class Meta:
        ordering = ["-name"]

    def __str__(self):
        return self.name

class Author(models.Model):
    SAL_LIST = (
        ('Mr', 'Mr'),
        ('Miss', 'Miss'),
        ('Mrs', 'Mrs'),
    )
    salutation = models.CharField(max_length=10, choices=SAL_LIST)
    name = models.CharField(max_length=200)
    email = models.EmailField()
    headshot = models.ImageField(upload_to='author_headshots')

    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField('Author')
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    publication_date = models.DateField()

    def __str__(self):
        return self.title


class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = RichTextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

class Project(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class API(models.Model):
    METHOD_LIST = (
        ('GET', 'GET'),
        ('POST', 'POST'),
    )
    STATUS_LIST = (
        ('200', '200'),
        ('404', '404'),
        ('301', '301'),
        ('401', '401'),
    )
    CONTENT_LIST = (
        ('application/json', 'application/json'),
        ('application/xml', 'application/xml'),
        ('text/json', 'text/json'),
        ('text/xml', 'text/xml'),
        ('raw', 'raw'),
    )

    path = models.CharField(max_length=50, help_text="API Path")
    method = models.CharField(max_length=10, choices=METHOD_LIST, help_text="Response Method")
    res_status = models.CharField(max_length=10, choices=STATUS_LIST, help_text="Response Status")
    content_type = models.CharField(max_length=50, choices=CONTENT_LIST)
    response_body = RichTextField()
    response_delay = models.CharField(max_length=20,blank=True,default="0", help_text="Response Delay In Seconds")
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __str__(self):
        return self.path

practice/views.py
import json
import time

from django.shortcuts import render,get_object_or_404 ,get_list_or_404
from django.views import generic
from django.core.urlresolvers import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.utils import timezone
from django.http import HttpResponse
from django.views.generic import ListView
from django.utils.safestring import mark_safe
from django.utils.text import unescape_entities
from django.utils.html import strip_tags
from django.views.decorators.csrf import csrf_exempt

from .models import Publisher, Author,Post,Project,API

class AuthorCreate(CreateView):
    model = Author
    fields = ['name']

class AuthorUpdate(UpdateView):
    model = Author
    fields = ['name']

class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('author-list')

class PublisherList(ListView):
    model = Publisher
    template_name = "practice/publisherlist.html"

class PostView(generic.ListView):
    template_name = 'practice/post_list.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'practice/blog_detail.html', {'post': post})

@csrf_exempt
def api_response(request, project_name , api_name):
    project = get_object_or_404(Project, name=project_name)
    api = get_object_or_404(API, project=project , path=api_name)
    data = api.response_body

    if api.content_type in ["application/json" , "text/json"]:
        data = json.dumps(strip_tags(mark_safe(data)))
        data = json.loads(data)
    elif api.content_type in ["application/xml" ,"text/xml"]:
        data = unescape_entities(strip_tags(mark_safe(data)))
    else:
        data = mark_safe(data)

    data = data.replace("&quot;","\"").replace("&nbsp;","")

    if request.method == api.method.upper():
        if api.response_delay not in ["0", ""] :
            time.sleep(int(api.response_delay))
        return HttpResponse(data, content_type=api.content_type, status=int(api.res_status))
    else:
        data = "Not Valid Method. Request method should be %s" % (api.method.upper())
        return HttpResponse(data)

def api_list(request, project_name):
    project_url = request.build_absolute_uri()
    project = get_object_or_404(Project, name=project_name)
    api = get_list_or_404(API.objects.order_by('path'), project=project)

    return render(request, 'practice/api_list.html', {'api_list': api,'project_name':project_name,'project_url':project_url})

def project_list(request):
    project_url = request.build_absolute_uri()
    project = Project.objects.all()
    return render(request, 'practice/project_list.html', {'project_list': project,'project_url':project_url})

practice/templates/practice/api_list.html
{% load staticfiles %}
<html>

<head>
  <title>{{project_name}}</title>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>

</head>

<body>
  <div class="card-panel teal lighten-2"  >
    <h5>{{project_name}} APIs :</h5>
  </div>
  <div class="content container">
    <ul class="collapsible" data-collapsible="accordion">
      {% for api in api_list %}
      <li>
        <div class="collapsible-header"><i class="material-icons">view_list</i><a href="{{project_url}}{{api}}" class="collection-item">{{ api }}</a></div>
        <div class="collapsible-body">
          <table class="responsive-table bordered striped centered">
            <thead>
              <tr>
                <th data-field="path">Path</th>
                <th data-field="method">Method</th>
                <th data-field="resst">Response Status</th>
                <th data-field="contype">Content Type</th>
                <th data-field="resdelay">Response Delay</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>{{project_url}}{{api}}</td>
                <td>{{api.method}}</td>
                <td>{{api.res_status}}</td>
                <td>{{api.content_type}}</td>
                <td>{{api.response_delay}}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </li>
      {% endfor %}
    </ul>
  </div>
</body>

</html>

practice/templates/practice/base.html
{% load staticfiles %}
<html>
    <head>
        <title>Blog</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    </head>
    <body>
      <div class="page-header">
        <h1><a href="/practice/posts">Blog</a></h1>
      </div>
     <div class="content container">
         <div class="row">
             <div class="col-md-8">
             {% block content %}
             {% endblock %}
             </div>
         </div>
     </div>
    </body>
</html>

practice/templates/practice/blog_detail.html
{% extends 'practice/base.html' %}

{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% endif %}
        <h3>{{ post.title }}</h3>
        <h5 class="author">By {{post.author}}</h5><br>
        <p>{{ post.text|safe|linebreaks }}</p>
    </div>
{% endblock %}

practice/templates/practice/post_list.html
{% extends 'practice/base.html' %}

{% block content %}
    {% for post in post_list %}
        <div class="post">
            <div class="date">
                {{ post.published_date }}
            </div>
            <h3><a href="{% url 'practice:post_detail' pk=post.pk %}">{{ post.title }}</a></h3>
            <h5 class="author">By {{post.author}}</h5>
            {{ post.text|safe|truncatewords:"50"|linebreaks }}
            <a href="{% url 'practice:post_detail' pk=post.pk %}">read more</a>
        </div>
        <hr>
    {% endfor %}
{% endblock %}

practice/templates/practice/project_list.html
{% load staticfiles %}
<html>

<head>
  <title>Projects</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>

</head>

<body>
  <div class="card-panel teal lighten-2">
    <h5>Projects:</a></h5>
  </div>
  <div class="content container">
    <ul class="collapsible" data-collapsible="accordion">
      {% for project in project_list %}
      <li>
        <div class="collapsible-header"><i class="material-icons">description</i><a href="{{project_url}}{{ project }}" class="collection-item">{{ project }}</a></div>
        <div class="collapsible-body"><p><b>Path :</b> {{project_url}}{{ project }}</p></div>
      </li>
      {% endfor %}
    </ul>
    </div>
  </div>
</body>
</html>

practice/templates/practice/publisherlist.html
{% block content %}
    <h2>Publishers</h2>
    <ul>
        {% for publisher in object_list %}
            <li>{{ publisher.name }}</li>
        {% endfor %}
    </ul>
{% endblock %}